### ISSUE TITLE
fitlog init 是否可以应用在已存在的git仓库内部？

### ISSUE THREAD

**Issue by xfarmer** [fastnlp/fitlog#22]
fitlog管理的git是否会和外部的git冲突？

**Comment by yhcc** [comment]
可以，fitlog管理的git是和您自己的git平行的。我们会在您的.gitignore文件中忽略掉fitlog管理的git文件的。

**Comment by zhouxiaowei1120** [comment]
在已存在的git仓库内部, 执行fitlog init 会报错。提示如下：

`$ fitlog init
Traceback (most recent call last):
  File "/Users/zhou/miniconda3/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhou/example/.fitlog' -> '/Users/zhou/example/.git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhou/miniconda3/bin/fitlog", line 8, in <module>
    sys.exit(main_cmd())
  File "/Users/zhou/miniconda3/lib/python3.7/site-packages/fitlog/fastcmd/__init__.py", line 49, in main_cmd
    cmd_map[cmd](argv)
  File "/Users/zhou/miniconda3/lib/python3.7/site-packages/fitlog/fastcmd/init_cmd.py", line 26, in init_cmd
    committer.init_project(name, hide=args["--hide"], git=not args["--no-git"])
  File "/Users/zhou/miniconda3/lib/python3.7/site-packages/fitlog/fastgit/committer.py", line 496, in init_project
    self._switch_to_fast_git(pj_path)
  File "/Users/zhou/miniconda3/lib/python3.7/site-packages/fitlog/fastgit/committer.py", line 167, in _switch_to_fast_git
    shutil.move(fitlog_path, git_path)
  File "/Users/zhou/miniconda3/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/Users/zhou/miniconda3/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/zhou/miniconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhou/example/.fitlog'`


希望能修复。十分感谢！
