### ISSUE TITLE
wsl环境下报错

### ISSUE THREAD

**Issue by kylinat2688** [fastnlp/fitlog#44]
环境：win10 wsl ubuntu20.4 python3.7
fitlog init报权限问题，再执行一次提示成功
Traceback (most recent call last):
  File "/mnt/d/Ubuntu/miniconda3/envs/test/bin/fitlog", line 8, in <module>
    sys.exit(main_cmd())
  File "/mnt/d/Ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/fitlog/fastcmd/__init__.py", line 49, in main_cmd
    cmd_map[cmd](argv)
  File "/mnt/d/Ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/fitlog/fastcmd/init_cmd.py", line 26, in init_cmd
    committer.init_project(name, hide=args["--hide"], git=not args["--no-git"])
  File "/mnt/d/Ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/fitlog/fastgit/committer.py", line 504, in init_project
    shutil.copytree(os.path.join(tools_path, "logs"), os.path.join(pj_path, "logs"))
  File "/mnt/d/Ubuntu/miniconda3/envs/test/lib/python3.7/shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('/mnt/d/Ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/fitlog/fastgit/normal/logs', '/mnt/d/Github/extest/logs', "[Errno 13] Permission denied: '/mnt/d/Github/extest/logs'")]

**Comment by yhcc** [comment]
感觉是权限问题～
