### ISSUE TITLE
请教一下fitlog如何使用

### ISSUE THREAD

**Issue by 12314123123** [fastnlp/fitlog#64]
我在gitbase里克隆了这个项目，然后按照说明书也初始化了项目，输入fitlog log logs后显示如下
$ fitlog log logs
This server will automatically shutdown if no api access for 48 hours.
Start preparing data...
Traceback (most recent call last):
  File "D:\Python\Python310\Scripts\fitlog-script.py", line 33, in <module>
    sys.exit(load_entry_point('fitlog==0.9.14', 'console_scripts', 'fitlog')())
  File "D:\Python\Python310\lib\site-packages\fitlog\fastcmd\__init__.py", line 49, in main_cmd
    cmd_map[cmd](argv)
  File "D:\Python\Python310\lib\site-packages\fitlog\fastcmd\log_cmd.py", line 52, in log_cmd
    start_app(log_dir, log_config_name, start_port, standby_hours, ip, token)
  File "D:\Python\Python310\lib\site-packages\fitlog\fastserver\app.py", line 93, in start_app
    all_data.update(prepare_data(log_reader, all_data['root_log_dir'], all_data['log_config_name']))
  File "D:\Python\Python310\lib\site-packages\fitlog\fastserver\server\table_utils.py", line 394, in prepare_data
    logs, configs, extra_data = get_log_and_extra_based_on_config(log_reader, log_dir, log_config_name)
  File "D:\Python\Python310\lib\site-packages\fitlog\fastserver\server\table_utils.py", line 340, in get_log_and_extra_based_on_config
    log_reader.set_log_dir(log_dir)
  File "D:\Python\Python310\lib\site-packages\fitlog\fastlog\log_read.py", line 35, in set_log_dir
    raise RuntimeError("`{}` has no valid logs. You should run your program first.".format(log_dir))
RuntimeError: `D:\fitlog\example\logs` has no valid logs. You should run your program first.
这个没有运行项目我不太明白，是需要我另外跑一个程序吗？有点懵圈

**Comment by 12314123123** [comment]
问题已经解决了
